//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Ericmas001.WebService.OmgPokedex.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatchedPokemonEntity
    {
        public int IdCatchedPokemon { get; set; }
        public int IdBackpack { get; set; }
        public int IdPokemonSummary { get; set; }
        public string Notes { get; set; }
    
        public virtual BackpackEntity Backpack { get; set; }
        public virtual PokemonSummaryEntity PokemonSummary { get; set; }
    }
}
