//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmgPokedex.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackpackEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BackpackEntity()
        {
            this.CatchedPokemonsOfBackpack = new HashSet<CatchedPokemonEntity>();
        }
    
        public int IdBackPack { get; set; }
        public int IdTrainer { get; set; }
        public string Name { get; set; }
    
        public virtual TrainerEntity Trainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatchedPokemonEntity> CatchedPokemonsOfBackpack { get; set; }
    }
}
