//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmgPokedex.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainerEntity()
        {
            this.BackpacksOfTrainer = new HashSet<BackpackEntity>();
        }
    
        public int IdTrainer { get; set; }
        public int IdUser { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackpackEntity> BackpacksOfTrainer { get; set; }
        public virtual UserEntity User { get; set; }
    }
}
